import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync, renameSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, sep } from "node:path";
import { execFileSync } from "node:child_process";
import { snapshot } from "./git";
import { parseOptions } from "./options";
import { run } from "./run";
const roots: string[] = [];
function git(root: string, ...args: string[]) { return execFileSync("git", ["-c", "core.hooksPath=/dev/null", "-c", "commit.gpgsign=false", ...args], { cwd: root, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim(); }
function put(root: string, path: string, content: string) { mkdirSync(join(root, path, ".."), { recursive: true }); writeFileSync(join(root, path), content); }
function repo() { const root = mkdtempSync(join(tmpdir(), "nodedots-cli-")); roots.push(root); git(root, "init"); git(root, "config", "user.email", "fixture@example.invalid"); git(root, "config", "user.name", "Fixture"); git(root, "config", "core.autocrlf", "false"); put(root, "src/app.ts", "export const version = 1;\n"); put(root, ".env.example", ""); git(root, "add", "."); git(root, "commit", "-m", "base"); return root; }
afterEach(() => { for (const root of roots.splice(0)) {
    if (resolve(root).startsWith(resolve(tmpdir()) + sep + "nodedots-cli-"))
        rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
} });
const options = (root: string, ...args: string[]) => parseOptions(["check", ...args], root);
async function command(root: string, ...args: string[]) { let out = "", err = ""; const code = await run(["check", ...args], root, s => out += s, s => err += s); return { code, out, err }; }
// Real Git subprocesses compete with the full suite on Windows.
describe("local Pre-flight snapshots", { timeout: 30000 }, () => {
    it("distinguishes staged from unstaged content", async () => { const root = repo(); put(root, "src/app.ts", "export const version = 2;\n"); git(root, "add", "."); put(root, "src/app.ts", "export const version = 3;\n"); expect((await snapshot(options(root, "--staged"))).input.changes[0].head).toContain("= 2"); expect((await snapshot(options(root))).input.changes[0].head).toContain("= 3"); });
    it("reads committed snapshots despite dirty local files", async () => { const root = repo(); put(root, "src/app.ts", "export const version = 2;\n"); git(root, "add", "."); git(root, "commit", "-m", "head"); put(root, "src/app.ts", "export const version = 9;\n"); const result = await snapshot(options(root, "--base", "HEAD~1", "--head", "HEAD")); expect(result.input.changes[0].base).toContain("= 1"); expect(result.input.changes[0].head).toContain("= 2"); expect(result.metadata.mode).toBe("commits"); });
    it("includes untracked files only when requested and ignores ignored files", async () => { const root = repo(); put(root, "new file.ts", "export const extra = 1;\n"); put(root, ".gitignore", "ignored.ts\n"); put(root, "ignored.ts", "export const hidden = 1;\n"); expect((await snapshot(options(root))).metadata.selectedChanges).toBe(0); const result = await snapshot(options(root, "--include-untracked")); expect(result.input.changes.map(c => c.path)).toContain("new file.ts"); expect(result.input.changes.map(c => c.path)).not.toContain("ignored.ts"); });
    it("preserves deletions and staged additions", async () => { const root = repo(); rmSync(join(root, "src/app.ts")); put(root, "src/added.ts", "export const added = true;\n"); git(root, "add", "."); const changes = (await snapshot(options(root, "--staged"))).input.changes; expect(changes.find(c => c.path === "src/app.ts")?.head).toBeNull(); expect(changes.find(c => c.path === "src/added.ts")?.base).toBeNull(); });
    it("does not count identical files with refreshed timestamps as changes", async () => { const root = repo(); put(root, "src/app.ts", "export const version = 1;\n"); expect((await snapshot(options(root))).metadata.selectedChanges).toBe(0); });
    it("does not read private configuration even when selected as env inventory", async () => { const root = repo(); put(root, ".env.local", "SECRET=never-output-this\n"); put(root, "secret.pem", "never-output-this"); const result = await snapshot(options(root, "--include-untracked", "--env-example", ".env.local")); expect(result.input.changes).toHaveLength(0); expect(result.input.retrievalNotes?.skipped).toHaveLength(2); expect(JSON.stringify(result)).not.toContain("never-output-this"); });
    it("reports unsupported changed files as incomplete", async () => { const root = repo(); put(root, "service.py", "print('hello')\n"); const result = await command(root, "--include-untracked", "--require-full", "--format", "json"); expect(result.code).toBe(3); expect(JSON.parse(result.out).report.coverage.completeness).toBe("unsupported"); });
    it("reports oversized source rather than inventing a deletion", async () => { const root = repo(); put(root, "src/app.ts", "x".repeat(1000001)); const result = await snapshot(options(root)); expect(result.input.changes).toHaveLength(0); expect(result.input.retrievalNotes?.skipped[0].reason).toContain("1 MB"); });
    it("handles spaces and Unicode in Git inventories", async () => { const root = repo(); put(root, "src/hello world é.ts", "export const greeting = true;\n"); git(root, "add", "."); expect((await snapshot(options(root, "--staged"))).input.changes[0].path).toBe("src/hello world é.ts"); });
    it("never invokes repository clean filters", async () => { const root = repo(); put(root, ".gitattributes", "*.ts filter=probe\n"); git(root, "config", "filter.probe.clean", "echo invoked > filter-invoked.txt"); put(root, "src/app.ts", "export const version = 2;\n"); await snapshot(options(root)); expect(existsSync(join(root, "filter-invoked.txt"))).toBe(false); });
    it("rejects linked parent directories without reading their content", async () => { const root = repo(); renameSync(join(root, "src"), join(root, "original")); put(root, "outside/app.ts", "export const secret = 'external-marker';\n"); symlinkSync(join(root, "outside"), join(root, "src"), process.platform === "win32" ? "junction" : "dir"); const result = await snapshot(options(root)); expect(result.input.retrievalNotes?.skipped.some(s => s.reason.includes("linked directory"))).toBe(true); expect(JSON.stringify(result)).not.toContain("external-marker"); });
    it("rejects unresolved index conflicts", async () => { const root = repo(); git(root, "checkout", "-b", "other"); put(root, "src/app.ts", "export const version = 2;\n"); git(root, "add", "."); git(root, "commit", "-m", "other"); git(root, "checkout", "-"); put(root, "src/app.ts", "export const version = 3;\n"); git(root, "add", "."); git(root, "commit", "-m", "main"); try {
        git(root, "merge", "other");
    }
    catch { } const result = await command(root, "--staged"); expect(result.code).toBe(2); expect(result.err).toContain("Resolve merge conflicts"); });
    it("creates engine findings and optional finding gates", async () => { const root = repo(); put(root, "src/app.ts", "export const token = process.env.NEW_TOKEN;\n"); const result = await command(root, "--format", "json", "--fail-on", "low"); const json = JSON.parse(result.out); expect(json.report.missing.length).toBeGreaterThan(0); expect(result.code).toBe(1); expect(json.advisory).toBe(true); expect((await command(root)).code).toBe(0); });
    it("returns a safe runtime error for missing refs", async () => { const root = repo(); const result = await command(root, "--base", "missing-reference"); expect(result.code).toBe(2); expect(result.out).toBe(""); expect(result.err).toContain("local object availability"); });
    it("rejects incompatible modes and external inventory paths", () => { expect(() => options(".", "--head", "HEAD", "--staged")).toThrow(); expect(() => options(".", "--staged", "--include-untracked")).toThrow(); expect(() => options(".", "--env-example", "../secret")).toThrow(); expect(() => options(".", "--format", "xml")).toThrow(); });
});
