export type Guide={slug:string;title:string;description:string;category:string;sections:{id:string;title:string;paragraphs:string[];steps?:string[];commands?:string[]}[]};
export const guides:Guide[]=[
 {slug:"pre-flight-cli",title:"Check before you push",description:"Run NodeDots locally on working changes, staged files, or two commits. Source preview for Node.js 22+.",category:"Pre-flight CLI",sections:[
  {id:"build",title:"Build the source preview",paragraphs:["The CLI is available from the NodeDots source repository. It is not published to npm yet. You need Node.js 22 or newer and Git. No GitHub sign-in, App installation, or running web server is required."],commands:["git clone https://github.com/0x-Sigmoid/nodedots.git\ncd nodedots\nnpm ci\nnpm run cli:build\nnpm run preflight -- --staged"]},
  {id:"repository",title:"Check your repository",paragraphs:["Use --cwd to check another local repository. The default compares tracked working-tree contents with HEAD. Untracked files are excluded unless explicitly requested; ignored files remain excluded."],commands:["node packages/cli/dist/nodedots.cjs check --cwd /path/to/repository\nnode packages/cli/dist/nodedots.cjs check --cwd /path/to/repository --include-untracked"]},
  {id:"snapshots",title:"Choose the right snapshot",paragraphs:["--staged reads Git index contents and ignores unstaged edits. --base and --head compare committed snapshots and ignore local file contents. The comparison is direct: choose a merge-base yourself if your workflow needs one. Required commits must already exist locally. Resolve index conflicts and create a first commit before checking."],commands:["npm run preflight -- --staged\nnpm run preflight -- --base HEAD~1 --head HEAD --format json"]},
  {id:"install",title:"Install the standalone command",paragraphs:["After building, pack the local package and install its archive. The bundle needs Node and Git and has no runtime npm dependencies. Use the generated archive path if you run these commands outside the source root."],commands:["npm pack ./packages/cli\nnpm install --global ./nodedots-cli-0.1.0.tgz\nnodedots check --staged\nnodedots check --help"]},
  {id:"policy",title:"Use optional failure policies",paragraphs:["Reports are advisory by default. --fail-on high, medium, or low returns exit 1 when a non-uncertain observation meets that threshold. --require-full returns exit 3 for incomplete coverage or withheld findings and takes precedence over finding gates. Exit 2 means input or runtime failure. Exit 0 only means the selected policy passed; it does not establish safety.","JSON output on stdout includes schemaVersion, cliVersion, the selected snapshot, exitCode, and the engine report. Errors go to stderr. In CI, make both commit objects available and install a built source artifact. No hooks or branch protection are configured automatically."],commands:["nodedots check --staged --fail-on high --require-full\nnodedots check --base HEAD~1 --head HEAD --format json > preflight.json"]},
  {id:"scope",title:"Read the limits with the findings",paragraphs:["Pre-flight uses deterministic analysis for supported JavaScript, TypeScript, Prisma, test-import, and environment-reference patterns. It performs no external AI calls, source uploads, fetching, fixes, or repository-code execution. Git clean filters and filesystem-monitor helpers are disabled for reads. Local checks can examine public or private repositories you can access; hosted beta repository restrictions are separate.","Private .env files, .dev.vars, credential extensions, linked paths, generated files, dependencies, binary content, and unsupported changes are excluded with coverage notes. Use .env.example or --env-example for a non-secret inventory. Source evidence may appear in reports; handle exported output accordingly.","Limits are 1 MB per file, 500 changed files, 10,000 eligible files, and 100 MB each for Git blobs and working content. Dynamic relationships, graph limits, omitted findings, and unsupported patterns remain limitations. Keep tests and human review in your shipping workflow."]}
 ]},
 {slug:"getting-started",title:"Your first pull request review",description:"Connect GitHub, choose a public repository, and follow the impact of a change.",category:"Start here",sections:[
  {id:"connect",title:"Connect your repository",paragraphs:["NodeDots Code reviews supported static relationships in JavaScript and TypeScript repositories. The current beta supports public repositories. You need a GitHub account and access to a repository connected to the NodeDots Code GitHub App."],steps:["Choose Get Started and sign in with GitHub.","Install NodeDots Code on your account or organization. Select the repositories you want to connect; an organization may require an administrator’s approval.","Return to onboarding and open the workspace. Choose your GitHub account and repository."]},
  {id:"review",title:"Run the first review",paragraphs:["Use an existing open pull request. NodeDots reads source at the captured base and head commits; it does not run your repository code."],steps:["Find a PR in Review inbox or paste its GitHub pull request URL.","Choose Review. The progress page shows retrieval, mapping, checking, and report preparation.","Open the completed report. Inspect source evidence, affected files, scope, and unknowns."]},
  {id:"next",title:"Before you merge",paragraphs:["Keep your tests and human review. A report with no observations only describes the examined scope. Configure Shipping setup, record your assessments, and recheck whenever the PR head or base changes."]}
 ]},
 {slug:"reviewing-changes",title:"Read the connected review",description:"Understand the impact map, source evidence, finding states, and saved decisions.",category:"Review",sections:[
  {id:"evidence",title:"Start with the evidence",paragraphs:["The impact map connects changed and affected files using relationships recorded by the analysis engine. Select a file or observation to inspect the consequence, source location, confidence explanation, and suggested next step. Source links point to the reviewed commit, rather than a moving branch.","The map displays up to 24 files. Scope & unknowns describes the broader examined scope, skipped files, and relationships that could not be established."]},
  {id:"states",title:"States describe different kinds of evidence",paragraphs:["Confirmed means supported evidence agrees. Missing means something expected is absent from the checked scope. Conflicting means connected parts disagree. Uncertain means the evidence needs verification. Action required means a decision or follow-up is needed.","Severity, confidence, coverage, and your decision are separate. A high-confidence finding does not guarantee that an entire change is safe."]},
  {id:"decisions",title:"Record a decision",paragraphs:["Accepted acknowledges an observation. Dismissed records disagreement. Fixed and intentional record your own assessment. Add a reason for context, or clear the decision to revisit it. A saved decision does not prove that a fix was tested.","Decisions belong to one user and one retained report. Rechecking creates a new report; decisions do not automatically transfer between commits."]},
  {id:"recheck",title:"Recheck after changes",paragraphs:["Recheck latest commit captures the current base and head. Comparison highlights new, persisting, and no-longer-observed fingerprints against your previous eligible report. Disappearance alone is not proof of a fix. Reports and jobs are available for seven days."]}
 ]},
 {slug:"shipping",title:"Prepare a change to ship",description:"Set repository expectations, add intent, inspect CI, and record release preparation.",category:"Ship",sections:[
  {id:"policy",title:"Configure shipping policy",paragraphs:["Open Shipping setup for the selected repository. An administrator or maintainer can set critical path prefixes, exact required CI names, expected GitHub reviewers, acknowledgment policy, and team release practices.","Policies are shared with authorized users of the connected repository. Concurrent changes require a reload so one maintainer cannot silently overwrite another’s policy."],steps:["List critical paths such as src/auth/ or db/.","Enter required check names exactly as GitHub displays them.","Add expected reviewer usernames and choose which observations need acknowledgment.","Record your team’s release practices and save the policy."]},
  {id:"intent",title:"Write the intent before implementation",paragraphs:["Repository writers can create a brief for a real PR number: intended outcome, acceptance criteria, and constraints. Load an existing brief before editing it. Acceptance criteria become human-assessed checklist items; NodeDots does not claim to execute or prove them."]},
  {id:"readiness",title:"Inspect independent readiness signals",paragraphs:["Each review shows commit freshness, coverage, unknown areas, recorded acknowledgments, GitHub checks, reviewer approvals, and release preparation. There is no aggregate safety score.","CI is fetched for the reviewed head. Passed, failed, pending, neutral, skipped, and unavailable remain distinct. A missing or ambiguous required name is unavailable. Approvals must match the reviewed head; unavailable or truncated review history cannot establish approval.","If the head or base has changed, recheck. Refresh signals to retrieve a new CI snapshot. These views are advisory and do not configure GitHub branch protection."]},
  {id:"release",title:"Record release preparation",paragraphs:["The checklist combines tests, documentation, rollout and recovery plans, analysis next steps, relevant schema/configuration paths, critical areas, team practices, and acceptance criteria. Done and not-applicable assessments require evidence or a reason. The actor and time remain visible.","Assessments apply to this retained report. Treat them as human decisions and confirm current behavior before shipping."]}
 ]},
 {slug:"sharing",title:"Hand off a review",description:"Export the context and grant individual teammates access without making reports public.",category:"Collaborate",sections:[
  {id:"handoff",title:"Copy or download the handoff",paragraphs:["Reviewer handoff exports the reviewed commit, CI snapshot, consequences, source evidence, unknowns, recorded decisions, intent, and release assessments. Copy it or download a text file. NodeDots does not automatically send messages or publish the handoff.","An exported file is a snapshot. Its recipient should check current commits and CI before using it to make a shipping decision."]},
  {id:"access",title:"Grant named review access",paragraphs:["The report owner enters a GitHub username and chooses Grant review access. A grant alone is not enough: the recipient must sign in and have access to this repository through NodeDots. Shared reports appear in the recipient’s retained history.","Recipients can read the report, record their own finding decisions, and record release assessments. They cannot grant further access. A shared link is not a public or anonymous report."]},
  {id:"revoke",title:"Revoke or expire access",paragraphs:["The owner can revoke a grant in Reviewer handoff. Repository access is checked again on saved-report reads. Grants and release assessments expire with the report after seven days and are removed by scheduled cleanup. Exported copies are controlled by the person who downloaded or copied them."]}
 ]},
 {slug:"automatic-reviews",title:"Review new commits automatically",description:"Enable advisory GitHub reviews and understand delivery evidence.",category:"Automate",sections:[
  {id:"enable",title:"Enable automatic reviews",paragraphs:["A repository administrator or maintainer enables automatic reviews in Repository context. One maintainer manages automation for each installation/repository. New and updated supported pull requests can create commit-pinned reviews. Draft PRs and private repositories are excluded from automatic review in this beta.","GitHub displays an advisory NodeDots check with a neutral conclusion and a link to the initiating maintainer’s authenticated report. Reports are shared only when the owner grants access."]},
  {id:"delivery",title:"Check delivery, not just configuration",paragraphs:["Shipping setup checks App configuration, PR event subscription, webhook URL, and recent PR delivery for the repository when GitHub makes that metadata available. No recent delivery observed means delivery has not been established from the available history.","If automation is off, signing credentials are missing, or webhook verification is unavailable, review manually while the maintainer investigates. Turning automation off prevents queued automatic jobs from proceeding."]},
  {id:"operators",title:"For self-hosting operators",paragraphs:["Configure a GitHub App with Contents read, Pull requests read, Metadata read, and Checks write. Commit-status visibility may require Commit statuses read. Enable Pull request events and use /api/workspace/github on your app origin with the same webhook secret as the service.","Use Cloudflare D1, the nodedots-reviews queue, and the workspace consumer. Keep App keys, auth secrets, and runner credentials server-side. This public guide describes the hosted workflow; deployment-specific credentials belong in the operator’s secret manager."]}
 ]},
 {slug:"data-and-permissions",title:"Data, permissions, and limitations",description:"Know what NodeDots reads, stores, and leaves unknown.",category:"Understand",sections:[
  {id:"scope",title:"Supported scope",paragraphs:["The engine checks supported JavaScript/TypeScript relationships, selected routes, environment references, schemas, and test imports. Dynamic behavior, external services, unsupported languages, and truncated retrieval can remain unknown. Read the coverage notes on every report.","The hosted review path uses deterministic analysis and does not send source to an external AI provider. It never executes repository code, applies fixes, or merges changes."]},
  {id:"storage",title:"Stored information",paragraphs:["Cloudflare D1 stores account/session metadata, encrypted GitHub tokens and report contents, reviewer decisions, repository preferences, shipping policies, briefs, and sharing grants. A queued manual token is erased when the job completes or fails. Reports and jobs expire after seven days; sessions last at most eight hours.","Shipping policies and briefs remain until replaced or cleared. Removing a repository or uninstalling the App prevents access but does not automatically erase retained policy or brief records. See Privacy for the full current notice."]},
  {id:"controls",title:"Your controls",paragraphs:["Select repository access in GitHub App settings. Sign out to remove the current server session. Revoke report grants in the handoff panel. Unsubscribe using the link in a waitlist email. Do not include credentials or unrelated personal data in briefs, assessment notes, or support requests."]}
 ]},
 {slug:"troubleshooting",title:"Troubleshoot the workflow",description:"Resolve sign-in, repository visibility, interrupted reviews, and missing CI signals.",category:"Help",sections:[
  {id:"signin",title:"Sign-in does not complete",paragraphs:["Start sign-in again from onboarding rather than reusing an old callback URL. The login flow expires after ten minutes. Allow the necessary first-party cookies. If the problem persists, the operator should verify App client credentials and the exact callback URL for this environment."]},
  {id:"repository",title:"A repository is missing",paragraphs:["Choose the correct account and use Manage repositories to check the NodeDots App installation. An organization administrator may need to approve access or new permissions. Private repositories are unavailable in this beta. Refresh the inbox after updating access."]},
  {id:"jobs",title:"A review is interrupted",paragraphs:["The job page reports actual stages and failures. Retry an interrupted review from the inbox or history. New commits can supersede a captured snapshot; start a new review to capture the current head and base. An expired report cannot be restored through its old link."]},
  {id:"checks",title:"Checks or approvals are unavailable",paragraphs:["Confirm that CI ran on the report’s reviewed head. Match required names exactly. Neutral or skipped does not mean passed, and approvals for an older commit do not count as current approval. Refresh the signals, verify GitHub permissions, or inspect GitHub directly if a list is truncated."]},
  {id:"sharing",title:"A teammate cannot open the report",paragraphs:["Confirm the owner granted the correct username, the teammate is signed in, and the repository is available through that teammate’s NodeDots installation access. Check whether the report has expired or the grant was revoked."]}
 ]}
];
